# Custom Language File for Launcher Customizer

[ejs.app]
title = "가내수공업"

[ejs.landing]
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/go-tiger/TeamHandmade-Launcher"
supportLink = "https://github.com/go-tiger/TeamHandmade-Launcher/issues"